#Scarlette González
#Laboratorio semana 9


print("Primer programa")
M= input("Ingrese un número ")

Millas = float(M)
Milla= (M*1)
print("La cantidad en millas es", Millas )
Kilómetro= float(Millas)
Kilómetro= Millas * 1.609
print("La cantidad en Kilómetros es", Kilómetro)
Metro = float(M)
Metro= (Kilómetro * 1000)
print("La cantidad en metros es", Metro)
Pie = float(M)
Pie= (Metro *3.281)
print("La cantidad en pies es", Pie)
